import {
	FATPAPER_DOMAIN,
	ICE_SERVER_PORT,
	PROTOCOL,
	FATPAPER_LOGIN_URL,
	USER_SERVER_URL,
	MONOPOLY_SERVER_URL,
	ICE_SERVER_PATH,
} from "../global.config";

export const __PROTOCOL__ = PROTOCOL;
export const __MONOPOLYSERVER__ = MONOPOLY_SERVER_URL;
export const __USERSERVER__ = USER_SERVER_URL;
export const __LOGINPAGEURL__ = FATPAPER_LOGIN_URL;
export const __ICE_SERVER_PATH__ = ICE_SERVER_PATH;

export const __FATPAPER_HOST__ = FATPAPER_DOMAIN;
export const __ICE_SERVER_PORT__ = ICE_SERVER_PORT;
