export enum PlayerEvents {
	GetPropertiesList = "GetPropertiesList",
	SetPropertiesList = "SetPropertiesList",
	GainProperty = "GainProperty",
	LoseProperty = "LoseProperty",
	GetCardsList = "GetCardsList",
	SetCardsList = "SetCardsList",
	GainCard = "GainCard",
	LoseCard = "LoseCard",
	GetMoney = "GetMoney",
	SetMoney = "SetMoney",
	Gain = "Gain",
	Cost = "Cont",
	GetStop = "GetStop",
	SetStop = "SetStop",
	Walk = "Walk",
	Tp = "Tp",
	SetBankrupted = "SetBankrupted",
	GetIsBankrupted = "GetIsBankrupted",

	AnimationFinished = "AnimationFinished",
}
